-- MySQL Script generated by MySQL Workbench
-- Fri May  3 01:00:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema entregable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema entregable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `entregable` DEFAULT CHARACTER SET utf8mb4 ;
USE `entregable` ;

-- -----------------------------------------------------
-- Table `entregable`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`clases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `disponible` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `imagen` VARCHAR(45) NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_finalizacion` DATETIME NULL,
  `cupo_max` INT NULL,
  `clases_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clases_id`),
  INDEX `fk_cursos_clases1_idx` (`clases_id` ASC)  ,
  CONSTRAINT `fk_cursos_clases1`
    FOREIGN KEY (`clases_id`)
    REFERENCES `entregable`.`clases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`unidades_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`unidades_cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `fecha_inicio` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`bloques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `visibilidad` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`unidades_cursos_has_clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`unidades_cursos_has_clases` (
  `unidades_cursos_id` INT NOT NULL,
  `clases_id` INT NOT NULL,
  PRIMARY KEY (`unidades_cursos_id`, `clases_id`),
  INDEX `fk_unidades_cursos_has_clases_clases1_idx` (`clases_id` ASC)  ,
  INDEX `fk_unidades_cursos_has_clases_unidades_cursos1_idx` (`unidades_cursos_id` ASC)  ,
  CONSTRAINT `fk_unidades_cursos_has_clases_unidades_cursos1`
    FOREIGN KEY (`unidades_cursos_id`)
    REFERENCES `entregable`.`unidades_cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidades_cursos_has_clases_clases1`
    FOREIGN KEY (`clases_id`)
    REFERENCES `entregable`.`clases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`clases_has_bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`clases_has_bloques` (
  `clases_id` INT NOT NULL,
  `bloques_id` INT NOT NULL,
  PRIMARY KEY (`clases_id`, `bloques_id`),
  INDEX `fk_clases_has_bloques_bloques1_idx` (`bloques_id` ASC)  ,
  INDEX `fk_clases_has_bloques_clases1_idx` (`clases_id` ASC)  ,
  CONSTRAINT `fk_clases_has_bloques_clases1`
    FOREIGN KEY (`clases_id`)
    REFERENCES `entregable`.`clases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clases_has_bloques_bloques1`
    FOREIGN KEY (`bloques_id`)
    REFERENCES `entregable`.`bloques` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`cursos_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`cursos_has_usuarios` (
  `cursos_id` INT NOT NULL,
  `cursos_clases_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`cursos_id`, `cursos_clases_id`, `usuarios_id`),
  INDEX `fk_cursos_has_usuarios_usuarios1_idx` (`usuarios_id` ASC)  ,
  INDEX `fk_cursos_has_usuarios_cursos1_idx` (`cursos_id` ASC, `cursos_clases_id` ASC)  ,
  CONSTRAINT `fk_cursos_has_usuarios_cursos1`
    FOREIGN KEY (`cursos_id` , `cursos_clases_id`)
    REFERENCES `entregable`.`cursos` (`id` , `clases_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `entregable`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
